import React, { CSSProperties, MouseEventHandler } from 'react';
import type { IconType } from 'react-icons';
import * as Io from 'react-icons/io';
import * as Io5 from 'react-icons/io5';

import styles from './Icon.module.scss';

export enum Icons {
  Add = 'Add',
  AddCircle = 'AddCircle',
  AddCircleOutline = 'AddCircleOutline',
  Airplane = 'Airplane',
  Alarm = 'Alarm',
  Albums = 'Albums',
  Alert = 'Alert',
  AmericanFootball = 'AmericanFootball',
  Analytics = 'Analytics',
  Aperture = 'Aperture',
  Apps = 'Apps',
  Appstore = 'Appstore',
  Archive = 'Archive',
  ArrowBackLight = 'ArrowBackLight',
  ArrowForwardLight = 'ArrowForwardLight',
  ArrowBack = 'ArrowBack',
  ArrowDown = 'ArrowDown',
  ArrowDropdown = 'ArrowDropdown',
  ArrowDropdownCircle = 'ArrowDropdownCircle',
  ArrowDropleft = 'ArrowDropleft',
  ArrowDropleftCircle = 'ArrowDropleftCircle',
  ArrowDropright = 'ArrowDropright',
  ArrowDroprightCircle = 'ArrowDroprightCircle',
  ArrowDropup = 'ArrowDropup',
  ArrowDropupCircle = 'ArrowDropupCircle',
  ArrowForward = 'ArrowForward',
  ArrowRoundBack = 'ArrowRoundBack',
  ArrowRoundDown = 'ArrowRoundDown',
  ArrowRoundForward = 'ArrowRoundForward',
  ArrowRoundUp = 'ArrowRoundUp',
  ArrowUp = 'ArrowUp',
  At = 'At',
  Attach = 'Attach',
  Backspace = 'Backspace',
  Barcode = 'Barcode',
  Baseball = 'Baseball',
  Basket = 'Basket',
  Basketball = 'Basketball',
  BatteryDead = 'BatteryDead',
  BatteryFull = 'BatteryFull',
  BatteryCharging = 'BatteryCharging',
  Beaker = 'Beaker',
  Bed = 'Bed',
  Beer = 'Beer',
  Bicycle = 'Bicycle',
  Bluetooth = 'Bluetooth',
  Boat = 'Boat',
  Body = 'Body',
  Bonfire = 'Bonfire',
  Book = 'Book',
  Bookmark = 'Bookmark',
  Bookmarks = 'Bookmarks',
  Bowtie = 'Bowtie',
  Briefcase = 'Briefcase',
  Browsers = 'Browsers',
  Brush = 'Brush',
  Bug = 'Bug',
  Build = 'Build',
  Bulb = 'Bulb',
  Bus = 'Bus',
  Business = 'Business',
  Cafe = 'Cafe',
  Calculator = 'Calculator',
  Calendar = 'Calendar',
  Call = 'Call',
  Camera = 'Camera',
  Car = 'Car',
  Card = 'Card',
  Cart = 'Cart',
  Cash = 'Cash',
  Cellular = 'Cellular',
  Clipboard = 'Clipboard',
  Clock = 'Clock',
  Close = 'Close',
  CloseCircle = 'CloseCircle',
  CloseCircleOutline = 'CloseCircleOutline',
  Cloud = 'Cloud',
  CloudCircle = 'CloudCircle',
  CloudDone = 'CloudDone',
  CloudDownload = 'CloudDownload',
  CloudOutline = 'CloudOutline',
  CloudUpload = 'CloudUpload',
  Cloudy = 'Cloudy',
  CloudyNight = 'CloudyNight',
  Code = 'Code',
  CodeDownload = 'CodeDownload',
  CodeWorking = 'CodeWorking',
  Cog = 'Cog',
  ColorFill = 'ColorFill',
  ColorFilter = 'ColorFilter',
  ColorPalette = 'ColorPalette',
  ColorWand = 'ColorWand',
  Compass = 'Compass',
  Construct = 'Construct',
  Contact = 'Contact',
  Contacts = 'Contacts',
  Contract = 'Contract',
  Contrast = 'Contrast',
  Copy = 'Copy',
  Create = 'Create',
  Crop = 'Crop',
  Cube = 'Cube',
  Cut = 'Cut',
  Desktop = 'Desktop',
  Disc = 'Disc',
  Document = 'Document',
  DoneAll = 'DoneAll',
  Download = 'Download',
  Easel = 'Easel',
  Edit = 'Edit',
  Egg = 'Egg',
  Exit = 'Exit',
  Expand = 'Expand',
  Eye = 'Eye',
  EyeOff = 'EyeOff',
  Fastforward = 'Fastforward',
  Female = 'Female',
  Filing = 'Filing',
  Film = 'Film',
  FingerPrint = 'FingerPrint',
  Fitness = 'Fitness',
  Flag = 'Flag',
  Flame = 'Flame',
  Flash = 'Flash',
  Flashlight = 'Flashlight',
  FlashOff = 'FlashOff',
  Flask = 'Flask',
  Flower = 'Flower',
  Folder = 'Folder',
  FolderOpen = 'FolderOpen',
  Football = 'Football',
  Funnel = 'Funnel',
  Gift = 'Gift',
  GitBranch = 'GitBranch',
  GitCommit = 'GitCommit',
  GitCompare = 'GitCompare',
  GitMerge = 'GitMerge',
  GitNetwork = 'GitNetwork',
  GitPullRequest = 'GitPullRequest',
  Glasses = 'Glasses',
  Globe = 'Globe',
  Grid = 'Grid',
  Hammer = 'Hammer',
  Hand = 'Hand',
  Happy = 'Happy',
  Headset = 'Headset',
  Heart = 'Heart',
  HeartDislike = 'HeartDislike',
  HeartEmpty = 'HeartEmpty',
  HeartHalf = 'HeartHalf',
  Help = 'Help',
  HelpBuoy = 'HelpBuoy',
  HelpCircle = 'HelpCircle',
  HelpCircleOutline = 'HelpCircleOutline',
  Home = 'Home',
  Hourglass = 'Hourglass',
  Chatboxes = 'Chatboxes',
  Chatbubbles = 'Chatbubbles',
  Checkbox = 'Checkbox',
  CheckboxOutline = 'CheckboxOutline',
  Checkmark = 'Checkmark',
  CheckmarkCircle = 'CheckmarkCircle',
  CheckmarkCircleOutline = 'CheckmarkCircleOutline',
  IceCream = 'IceCream',
  Image = 'Image',
  Images = 'Images',
  Infinite = 'Infinite',
  Information = 'Information',
  InformationCircle = 'InformationCircle',
  InformationCircleOutline = 'InformationCircleOutline',
  Jet = 'Jet',
  Journal = 'Journal',
  Key = 'Key',
  Keypad = 'Keypad',
  Laptop = 'Laptop',
  Leaf = 'Leaf',
  Link = 'Link',
  List = 'List',
  ListBox = 'ListBox',
  Locate = 'Locate',
  Locked = 'Locked',
  LogIn = 'LogIn',
  LogOut = 'LogOut',
  Magnet = 'Magnet',
  Mail = 'Mail',
  MailOpen = 'MailOpen',
  MailUnread = 'MailUnread',
  Male = 'Male',
  Man = 'Man',
  Map = 'Map',
  Medal = 'Medal',
  Medical = 'Medical',
  Medkit = 'Medkit',
  Megaphone = 'Megaphone',
  Menu = 'Menu',
  Mic = 'Mic',
  MicOff = 'MicOff',
  Microphone = 'Microphone',
  Moon = 'Moon',
  More = 'More',
  Move = 'Move',
  MusicalNote = 'MusicalNote',
  MusicalNotes = 'MusicalNotes',
  Navigate = 'Navigate',
  Notifications = 'Notifications',
  NotificationsOff = 'NotificationsOff',
  NotificationsOutline = 'NotificationsOutline',
  Nuclear = 'Nuclear',
  Nutrition = 'Nutrition',
  Open = 'Open',
  Options = 'Options',
  Outlet = 'Outlet',
  Paper = 'Paper',
  PaperPlane = 'PaperPlane',
  PartlySunny = 'PartlySunny',
  Pause = 'Pause',
  Paw = 'Paw',
  People = 'People',
  Person = 'Person',
  PersonAdd = 'PersonAdd',
  PhoneLandscape = 'PhoneLandscape',
  PhonePortrait = 'PhonePortrait',
  Photos = 'Photos',
  Pin = 'Pin',
  Pint = 'Pint',
  Pizza = 'Pizza',
  Planet = 'Planet',
  Play = 'Play',
  Back = 'Back',
  Forward = 'Forward',
  PlayCircle = 'PlayCircle',
  Podium = 'Podium',
  Power = 'Power',
  Pricetag = 'Pricetag',
  Pricetags = 'Pricetags',
  Print = 'Print',
  Pulse = 'Pulse',
  QrScanner = 'QrScanner',
  Quote = 'Quote',
  Radio = 'Radio',
  RadioButtonOff = 'RadioButtonOff',
  RadioButtonOn = 'RadioButtonOn',
  Rainy = 'Rainy',
  Recording = 'Recording',
  Redo = 'Redo',
  Refresh = 'Refresh',
  RefreshCircle = 'RefreshCircle',
  Remove = 'Remove',
  RemoveCircle = 'RemoveCircle',
  RemoveCircleOutline = 'RemoveCircleOutline',
  Reorder = 'Reorder',
  Repeat = 'Repeat',
  Resize = 'Resize',
  Restaurant = 'Restaurant',
  ReturnLeft = 'ReturnLeft',
  ReturnRight = 'ReturnRight',
  ReverseCamera = 'ReverseCamera',
  Rewind = 'Rewind',
  Ribbon = 'Ribbon',
  Rocket = 'Rocket',
  Rose = 'Rose',
  Sad = 'Sad',
  Save = 'Save',
  Search = 'Search',
  Send = 'Send',
  Settings = 'Settings',
  Share = 'Share',
  ShareAlt = 'ShareAlt',
  Shirt = 'Shirt',
  Shuffle = 'Shuffle',
  School = 'School',
  SkipBackward = 'SkipBackward',
  SkipForward = 'SkipForward',
  Snow = 'Snow',
  Speedometer = 'Speedometer',
  Square = 'Square',
  SquareOutline = 'SquareOutline',
  Star = 'Star',
  StarHalf = 'StarHalf',
  StarOutline = 'StarOutline',
  Stats = 'Stats',
  Stopwatch = 'Stopwatch',
  Subway = 'Subway',
  Sunny = 'Sunny',
  Swap = 'Swap',
  Switch = 'Switch',
  Sync = 'Sync',
  TabletLandscape = 'TabletLandscape',
  TabletPortrait = 'TabletPortrait',
  Tennisball = 'Tennisball',
  Text = 'Text',
  Thermometer = 'Thermometer',
  ThumbsDown = 'ThumbsDown',
  ThumbsUp = 'ThumbsUp',
  Thunderstorm = 'Thunderstorm',
  Time = 'Time',
  Timer = 'Timer',
  Today = 'Today',
  Train = 'Train',
  Transgender = 'Transgender',
  Trash = 'Trash',
  TrendingDown = 'TrendingDown',
  TrendingUp = 'TrendingUp',
  Trophy = 'Trophy',
  Tv = 'Tv',
  Umbrella = 'Umbrella',
  Undo = 'Undo',
  Unlocked = 'Unlocked',
  Videocam = 'Videocam',
  VolumeHigh = 'VolumeHigh',
  VolumeLow = 'VolumeLow',
  VolumeMute = 'VolumeMute',
  VolumeOff = 'VolumeOff',
  Walk = 'Walk',
  Wallet = 'Wallet',
  Warning = 'Warning',
  Water = 'Water',
  Watch = 'Watch',
  Wifi = 'Wifi',
  Wine = 'Wine',
  Woman = 'Woman',
}

const IconsMap: Record<Icons, IconType> = {
  [Icons.Add]: Io5.IoAdd,
  [Icons.AddCircle]: Io5.IoAddCircle,
  [Icons.AddCircleOutline]: Io5.IoAddCircleOutline,
  [Icons.Airplane]: Io5.IoAirplane,
  [Icons.Alarm]: Io5.IoAlarm,
  [Icons.Albums]: Io5.IoAlbums,
  [Icons.Alert]: Io5.IoAlert,
  [Icons.AmericanFootball]: Io5.IoAmericanFootball,
  [Icons.Analytics]: Io5.IoAnalytics,
  [Icons.Aperture]: Io5.IoAperture,
  [Icons.Apps]: Io5.IoApps,
  [Icons.Appstore]: Io5.IoLogoAppleAppstore,
  [Icons.Archive]: Io5.IoArchive,
  [Icons.ArrowBackLight]: Io5.IoChevronBackOutline,
  [Icons.ArrowForwardLight]: Io5.IoChevronForwardOutline,
  [Icons.ArrowBack]: Io5.IoArrowBack,
  [Icons.ArrowDown]: Io5.IoArrowDown,
  [Icons.ArrowDropdown]: Io.IoMdArrowDropdown,
  [Icons.ArrowDropdownCircle]: Io.IoMdArrowDropdownCircle,
  [Icons.ArrowDropleft]: Io.IoMdArrowDropleft,
  [Icons.ArrowDropleftCircle]: Io.IoMdArrowDropleftCircle,
  [Icons.ArrowDropright]: Io.IoMdArrowDropright,
  [Icons.ArrowDroprightCircle]: Io.IoMdArrowDroprightCircle,
  [Icons.ArrowDropup]: Io.IoMdArrowDropup,
  [Icons.ArrowDropupCircle]: Io.IoMdArrowDropupCircle,
  [Icons.ArrowForward]: Io5.IoArrowForward,
  [Icons.ArrowRoundBack]: Io.IoMdArrowRoundBack,
  [Icons.ArrowRoundDown]: Io.IoMdArrowRoundDown,
  [Icons.ArrowRoundForward]: Io.IoMdArrowRoundForward,
  [Icons.ArrowRoundUp]: Io.IoMdArrowRoundUp,
  [Icons.ArrowUp]: Io5.IoArrowUp,
  [Icons.At]: Io5.IoAt,
  [Icons.Attach]: Io5.IoAttach,
  [Icons.Backspace]: Io5.IoBackspace,
  [Icons.Barcode]: Io5.IoBarcode,
  [Icons.Baseball]: Io5.IoBaseball,
  [Icons.Basket]: Io5.IoBasket,
  [Icons.Basketball]: Io5.IoBasketball,
  [Icons.BatteryDead]: Io5.IoBatteryDead,
  [Icons.BatteryFull]: Io5.IoBatteryFull,
  [Icons.BatteryCharging]: Io5.IoBatteryCharging,
  [Icons.Beaker]: Io5.IoBeaker,
  [Icons.Bed]: Io5.IoBed,
  [Icons.Beer]: Io5.IoBeer,
  [Icons.Bicycle]: Io5.IoBicycle,
  [Icons.Bluetooth]: Io5.IoBluetooth,
  [Icons.Boat]: Io5.IoBoat,
  [Icons.Body]: Io5.IoBody,
  [Icons.Bonfire]: Io5.IoBonfire,
  [Icons.Book]: Io5.IoBook,
  [Icons.Bookmark]: Io5.IoBookmark,
  [Icons.Bookmarks]: Io5.IoBookmarks,
  [Icons.Bowtie]: Io.IoIosBowtie,
  [Icons.Briefcase]: Io5.IoBriefcase,
  [Icons.Browsers]: Io5.IoBrowsers,
  [Icons.Brush]: Io5.IoBrush,
  [Icons.Bug]: Io5.IoBug,
  [Icons.Build]: Io5.IoBuild,
  [Icons.Bulb]: Io5.IoBulb,
  [Icons.Bus]: Io5.IoBus,
  [Icons.Business]: Io5.IoBusiness,
  [Icons.Cafe]: Io5.IoCafe,
  [Icons.Calculator]: Io5.IoCalculator,
  [Icons.Calendar]: Io5.IoCalendar,
  [Icons.Call]: Io5.IoCall,
  [Icons.Camera]: Io5.IoCamera,
  [Icons.Car]: Io5.IoCar,
  [Icons.Card]: Io5.IoCard,
  [Icons.Cart]: Io5.IoCart,
  [Icons.Cash]: Io5.IoCash,
  [Icons.Cellular]: Io5.IoCellular,
  [Icons.Clipboard]: Io5.IoClipboard,
  [Icons.Clock]: Io.IoIosClock,
  [Icons.Close]: Io5.IoClose,
  [Icons.CloseCircle]: Io5.IoCloseCircle,
  [Icons.CloseCircleOutline]: Io5.IoCloseCircleOutline,
  [Icons.Cloud]: Io5.IoCloud,
  [Icons.CloudCircle]: Io5.IoCloudCircle,
  [Icons.CloudDone]: Io5.IoCloudDone,
  [Icons.CloudDownload]: Io5.IoCloudDownload,
  [Icons.CloudOutline]: Io5.IoCloudOutline,
  [Icons.CloudUpload]: Io5.IoCloudUpload,
  [Icons.Cloudy]: Io5.IoCloudy,
  [Icons.CloudyNight]: Io5.IoCloudyNight,
  [Icons.Code]: Io5.IoCode,
  [Icons.CodeDownload]: Io5.IoCodeDownload,
  [Icons.CodeWorking]: Io5.IoCodeWorking,
  [Icons.Cog]: Io5.IoCog,
  [Icons.ColorFill]: Io5.IoColorFill,
  [Icons.ColorFilter]: Io5.IoColorFilter,
  [Icons.ColorPalette]: Io5.IoColorPalette,
  [Icons.ColorWand]: Io5.IoColorWand,
  [Icons.Compass]: Io5.IoCompass,
  [Icons.Construct]: Io5.IoConstruct,
  [Icons.Contact]: Io.IoIosContact,
  [Icons.Contacts]: Io.IoIosContacts,
  [Icons.Contract]: Io5.IoContract,
  [Icons.Contrast]: Io5.IoContrast,
  [Icons.Copy]: Io5.IoCopy,
  [Icons.Create]: Io5.IoCreate,
  [Icons.Crop]: Io5.IoCrop,
  [Icons.Cube]: Io5.IoCube,
  [Icons.Cut]: Io5.IoCut,
  [Icons.Desktop]: Io5.IoDesktop,
  [Icons.Disc]: Io5.IoDisc,
  [Icons.Document]: Io5.IoDocument,
  [Icons.DoneAll]: Io.IoMdDoneAll,
  [Icons.Download]: Io5.IoDownload,
  [Icons.Easel]: Io5.IoEasel,
  [Icons.Edit]: Io5.IoCreate,
  [Icons.Egg]: Io5.IoEgg,
  [Icons.Exit]: Io5.IoExit,
  [Icons.Expand]: Io5.IoExpand,
  [Icons.Eye]: Io5.IoEye,
  [Icons.EyeOff]: Io5.IoEyeOff,
  [Icons.Fastforward]: Io.IoMdFastforward,
  [Icons.Female]: Io5.IoFemale,
  [Icons.Filing]: Io.IoMdFiling,
  [Icons.Film]: Io5.IoFilm,
  [Icons.FingerPrint]: Io5.IoFingerPrint,
  [Icons.Fitness]: Io5.IoFitness,
  [Icons.Flag]: Io5.IoFlag,
  [Icons.Flame]: Io5.IoFlame,
  [Icons.Flash]: Io5.IoFlash,
  [Icons.Flashlight]: Io5.IoFlashlight,
  [Icons.FlashOff]: Io5.IoFlashOff,
  [Icons.Flask]: Io5.IoFlask,
  [Icons.Flower]: Io5.IoFlower,
  [Icons.Folder]: Io5.IoFolder,
  [Icons.FolderOpen]: Io5.IoFolderOpen,
  [Icons.Football]: Io5.IoFootball,
  [Icons.Funnel]: Io5.IoFunnel,
  [Icons.Gift]: Io5.IoGift,
  [Icons.GitBranch]: Io5.IoGitBranch,
  [Icons.GitCommit]: Io5.IoGitCommit,
  [Icons.GitCompare]: Io5.IoGitCompare,
  [Icons.GitMerge]: Io5.IoGitMerge,
  [Icons.GitNetwork]: Io5.IoGitNetwork,
  [Icons.GitPullRequest]: Io5.IoGitPullRequest,
  [Icons.Glasses]: Io5.IoGlasses,
  [Icons.Globe]: Io5.IoGlobe,
  [Icons.Grid]: Io5.IoGrid,
  [Icons.Hammer]: Io5.IoHammer,
  [Icons.Hand]: Io5.IoHandLeft,
  [Icons.Happy]: Io5.IoHappy,
  [Icons.Headset]: Io5.IoHeadset,
  [Icons.Heart]: Io5.IoHeart,
  [Icons.HeartDislike]: Io5.IoHeartDislike,
  [Icons.HeartEmpty]: Io.IoMdHeartEmpty,
  [Icons.HeartHalf]: Io5.IoHeartHalf,
  [Icons.Help]: Io5.IoHelp,
  [Icons.HelpBuoy]: Io5.IoHelpBuoy,
  [Icons.HelpCircle]: Io5.IoHelpCircle,
  [Icons.HelpCircleOutline]: Io5.IoHelpCircleOutline,
  [Icons.Home]: Io5.IoHome,
  [Icons.Hourglass]: Io5.IoHourglass,
  [Icons.Chatboxes]: Io.IoIosChatboxes,
  [Icons.Chatbubbles]: Io5.IoChatbubbles,
  [Icons.Checkbox]: Io5.IoCheckbox,
  [Icons.CheckboxOutline]: Io5.IoCheckboxOutline,
  [Icons.Checkmark]: Io5.IoCheckmark,
  [Icons.CheckmarkCircle]: Io5.IoCheckmarkCircle,
  [Icons.CheckmarkCircleOutline]: Io5.IoCheckmarkCircleOutline,
  [Icons.IceCream]: Io5.IoIceCream,
  [Icons.Image]: Io5.IoImage,
  [Icons.Images]: Io5.IoImages,
  [Icons.Infinite]: Io5.IoInfinite,
  [Icons.Information]: Io5.IoInformation,
  [Icons.InformationCircle]: Io5.IoInformationCircle,
  [Icons.InformationCircleOutline]: Io5.IoInformationCircleOutline,
  [Icons.Jet]: Io.IoMdJet,
  [Icons.Journal]: Io5.IoJournal,
  [Icons.Key]: Io5.IoKey,
  [Icons.Keypad]: Io5.IoKeypad,
  [Icons.Laptop]: Io5.IoLaptop,
  [Icons.Leaf]: Io5.IoLeaf,
  [Icons.Link]: Io5.IoLink,
  [Icons.List]: Io5.IoList,
  [Icons.ListBox]: Io.IoMdListBox,
  [Icons.Locate]: Io5.IoLocate,
  [Icons.Locked]: Io.IoIosLock,
  [Icons.LogIn]: Io5.IoLogIn,
  [Icons.LogOut]: Io5.IoLogOut,
  [Icons.Magnet]: Io5.IoMagnet,
  [Icons.Mail]: Io5.IoMail,
  [Icons.MailOpen]: Io5.IoMailOpen,
  [Icons.MailUnread]: Io5.IoMailUnread,
  [Icons.Male]: Io5.IoMale,
  [Icons.Man]: Io5.IoMan,
  [Icons.Map]: Io5.IoMap,
  [Icons.Medal]: Io5.IoMedal,
  [Icons.Medical]: Io5.IoMedical,
  [Icons.Medkit]: Io5.IoMedkit,
  [Icons.Megaphone]: Io5.IoMegaphone,
  [Icons.Menu]: Io5.IoMenu,
  [Icons.Mic]: Io5.IoMic,
  [Icons.MicOff]: Io5.IoMicOff,
  [Icons.Microphone]: Io.IoMdMicrophone,
  [Icons.Moon]: Io5.IoMoon,
  [Icons.More]: Io.IoIosMore,
  [Icons.Move]: Io5.IoMove,
  [Icons.MusicalNote]: Io5.IoMusicalNote,
  [Icons.MusicalNotes]: Io5.IoMusicalNotes,
  [Icons.Navigate]: Io5.IoNavigate,
  [Icons.Notifications]: Io5.IoNotifications,
  [Icons.NotificationsOff]: Io5.IoNotificationsOff,
  [Icons.NotificationsOutline]: Io5.IoNotificationsOutline,
  [Icons.Nuclear]: Io5.IoNuclear,
  [Icons.Nutrition]: Io5.IoNutrition,
  [Icons.Open]: Io5.IoOpen,
  [Icons.Options]: Io5.IoOptions,
  [Icons.Outlet]: Io.IoMdOutlet,
  [Icons.Paper]: Io5.IoNewspaper,
  [Icons.PaperPlane]: Io5.IoPaperPlane,
  [Icons.PartlySunny]: Io5.IoPartlySunny,
  [Icons.Pause]: Io5.IoPause,
  [Icons.Paw]: Io5.IoPaw,
  [Icons.People]: Io5.IoPeople,
  [Icons.Person]: Io5.IoPerson,
  [Icons.PersonAdd]: Io5.IoPersonAdd,
  [Icons.PhoneLandscape]: Io5.IoPhoneLandscape,
  [Icons.PhonePortrait]: Io5.IoPhonePortrait,
  [Icons.Photos]: Io.IoMdPhotos,
  [Icons.Pin]: Io5.IoPin,
  [Icons.Pint]: Io5.IoPint,
  [Icons.Pizza]: Io5.IoPizza,
  [Icons.Planet]: Io5.IoPlanet,
  [Icons.Play]: Io5.IoPlay,
  [Icons.Back]: Io5.IoCaretBackOutline,
  [Icons.Forward]: Io5.IoCaretForwardSharp ,
  [Icons.PlayCircle]: Io5.IoPlayCircle,
  [Icons.Podium]: Io5.IoPodium,
  [Icons.Power]: Io5.IoPower,
  [Icons.Pricetag]: Io5.IoPricetag,
  [Icons.Pricetags]: Io5.IoPricetags,
  [Icons.Print]: Io5.IoPrint,
  [Icons.Pulse]: Io5.IoPulse,
  [Icons.QrScanner]: Io.IoMdQrScanner,
  [Icons.Quote]: Io.IoIosQuote,
  [Icons.Radio]: Io5.IoRadio,
  [Icons.RadioButtonOff]: Io5.IoRadioButtonOff,
  [Icons.RadioButtonOn]: Io5.IoRadioButtonOn,
  [Icons.Rainy]: Io5.IoRainy,
  [Icons.Recording]: Io5.IoRecording,
  [Icons.Redo]: Io.IoMdRedo,
  [Icons.Refresh]: Io5.IoRefresh,
  [Icons.RefreshCircle]: Io5.IoRefreshCircle,
  [Icons.Remove]: Io5.IoRemove,
  [Icons.RemoveCircle]: Io5.IoRemoveCircle,
  [Icons.RemoveCircleOutline]: Io5.IoRemoveCircleOutline,
  [Icons.Reorder]: Io.IoMdReorder,
  [Icons.Repeat]: Io5.IoRepeat,
  [Icons.Resize]: Io5.IoResize,
  [Icons.Restaurant]: Io5.IoRestaurant,
  [Icons.ReturnLeft]: Io.IoIosReturnLeft,
  [Icons.ReturnRight]: Io.IoIosReturnRight,
  [Icons.ReverseCamera]: Io.IoMdReverseCamera,
  [Icons.Rewind]: Io.IoMdRewind,
  [Icons.Ribbon]: Io5.IoRibbon,
  [Icons.Rocket]: Io5.IoRocket,
  [Icons.Rose]: Io5.IoRose,
  [Icons.Sad]: Io5.IoSad,
  [Icons.Save]: Io5.IoSave,
  [Icons.Search]: Io5.IoSearch,
  [Icons.Send]: Io5.IoSend,
  [Icons.Settings]: Io5.IoSettings,
  [Icons.Share]: Io5.IoShare,
  [Icons.ShareAlt]: Io.IoIosShareAlt,
  [Icons.Shirt]: Io5.IoShirt,
  [Icons.Shuffle]: Io5.IoShuffle,
  [Icons.School]: Io5.IoSchool,
  [Icons.SkipBackward]: Io.IoIosSkipBackward,
  [Icons.SkipForward]: Io.IoIosSkipForward,
  [Icons.Snow]: Io5.IoSnow,
  [Icons.Speedometer]: Io5.IoSpeedometer,
  [Icons.Square]: Io5.IoSquare,
  [Icons.SquareOutline]: Io5.IoSquareOutline,
  [Icons.Star]: Io5.IoStar,
  [Icons.StarHalf]: Io5.IoStarHalf,
  [Icons.StarOutline]: Io5.IoStarOutline,
  [Icons.Stats]: Io.IoMdStats,
  [Icons.Stopwatch]: Io5.IoStopwatch,
  [Icons.Subway]: Io5.IoSubway,
  [Icons.Sunny]: Io5.IoSunny,
  [Icons.Swap]: Io.IoMdSwap,
  [Icons.Switch]: Io.IoIosSwitch,
  [Icons.Sync]: Io5.IoSync,
  [Icons.TabletLandscape]: Io5.IoTabletLandscape,
  [Icons.TabletPortrait]: Io5.IoTabletPortrait,
  [Icons.Tennisball]: Io5.IoTennisball,
  [Icons.Text]: Io5.IoText,
  [Icons.Thermometer]: Io5.IoThermometer,
  [Icons.ThumbsDown]: Io5.IoThumbsDown,
  [Icons.ThumbsUp]: Io5.IoThumbsUp,
  [Icons.Thunderstorm]: Io5.IoThunderstorm,
  [Icons.Time]: Io5.IoTime,
  [Icons.Timer]: Io5.IoTimer,
  [Icons.Today]: Io5.IoToday,
  [Icons.Train]: Io5.IoTrain,
  [Icons.Transgender]: Io5.IoTransgender,
  [Icons.Trash]: Io5.IoTrash,
  [Icons.TrendingDown]: Io5.IoTrendingDown,
  [Icons.TrendingUp]: Io5.IoTrendingUp,
  [Icons.Trophy]: Io5.IoTrophy,
  [Icons.Tv]: Io5.IoTv,
  [Icons.Umbrella]: Io5.IoUmbrella,
  [Icons.Undo]: Io5.IoArrowUndoSharp,
  [Icons.Unlocked]: Io.IoMdUnlock,
  [Icons.Videocam]: Io5.IoVideocam,
  [Icons.VolumeHigh]: Io5.IoVolumeHigh,
  [Icons.VolumeLow]: Io5.IoVolumeLow,
  [Icons.VolumeMute]: Io5.IoVolumeMute,
  [Icons.VolumeOff]: Io5.IoVolumeOff,
  [Icons.Walk]: Io5.IoWalk,
  [Icons.Wallet]: Io5.IoWallet,
  [Icons.Warning]: Io5.IoWarning,
  [Icons.Water]: Io5.IoWater,
  [Icons.Watch]: Io5.IoWatch,
  [Icons.Wifi]: Io5.IoWifi,
  [Icons.Wine]: Io5.IoWine,
  [Icons.Woman]: Io5.IoWoman,
};

export type IIconProps = {
  icon: Icons;
  style?: CSSProperties;
  className?: string;
  onClick?: MouseEventHandler;
  id?: string;
};

export function Icon({ icon, style, className, onClick, id }: IIconProps) {
  const IconComp = IconsMap[icon];

  return (
    <span id={id} onClick={onClick} className={`${styles.icon} ${className || ''}`} style={style}>
      <IconComp />
    </span>
  );
}