'use client';

import React, { CSSProperties, MouseEventHandler } from 'react';
import clx from 'classnames';
import styles from './Icon.module.scss';

import type { IconType } from 'react-icons';
import * as Io from 'react-icons/io';
import * as Io5 from 'react-icons/io5';

type IProps = {
  icon: Icons;               // <- bleibt so => keine 50 Files anfassen
  size?: number;
  style?: CSSProperties;
  className?: string;
  onClick?: MouseEventHandler<HTMLSpanElement>;
  id?: string;
  'data-testid'?: string;
};

const ICON_LIB: Record<string, IconType> = {
  ...(Io as unknown as Record<string, IconType>),
  ...(Io5 as unknown as Record<string, IconType>),
};

export function Icon({
  icon,
  size = 20,
  style,
  className,
  onClick,
  id,
  'data-testid': dataTestId,
}: IProps) {
  const IconComponent = ICON_LIB[String(icon)] ?? (Io.IoMdHelp as unknown as IconType);

  return (
    <span
      id={id}
      onClick={onClick}
      className={clx(styles.icon, className)}
      style={style}
      data-testid={dataTestId}
    >
      <IconComponent size={size} />
    </span>
  );
}

/**
 * WICHTIG:
 * - Keys bleiben GENAU wie deine Vorlage
 * - Values sind die react-icons Export-Namen als String (IoMd...)
 * - Damit geht `icon?: Icons` überall weiter
 * - Und `Icons.SkipForward` existiert wieder
 */
export enum Icons {
  Add = 'IoMdAdd',
  AddCircle = 'IoMdAddCircle',
  AddCircleOutline = 'IoMdAddCircleOutline',
  Airplane = 'IoMdPaperPlane',
  Alarm = 'IoMdAlarm',
  Albums = 'IoMdAlbums',
  Alert = 'IoMdAlert',
  AmericanFootball = 'IoMdAmericanFootball',
  Analytics = 'IoMdAnalytics',
  Aperture = 'IoMdAperture',
  Apps = 'IoMdApps',
  Appstore = 'IoMdAppstore',
  Archive = 'IoMdArchive',

  // "Light" gibts in react-icons so nicht -> wir nehmen die normalen
  ArrowBackLight = 'IoMdArrowBack',
  ArrowForwardLight = 'IoMdArrowForward',

  ArrowBack = 'IoMdArrowBack',
  ArrowDown = 'IoMdArrowDown',
  ArrowDropdown = 'IoMdArrowDropdown',
  ArrowDropdownCircle = 'IoMdArrowDropdownCircle',
  ArrowDropleft = 'IoMdArrowDropleft',
  ArrowDropleftCircle = 'IoMdArrowDropleftCircle',
  ArrowDropright = 'IoMdArrowDropright',
  ArrowDroprightCircle = 'IoMdArrowDroprightCircle',
  ArrowDropup = 'IoMdArrowDropup',
  ArrowDropupCircle = 'IoMdArrowDropupCircle',
  ArrowForward = 'IoMdArrowForward',
  ArrowRoundBack = 'IoMdArrowRoundBack',
  ArrowRoundDown = 'IoMdArrowRoundDown',
  ArrowRoundForward = 'IoMdArrowRoundForward',
  ArrowRoundUp = 'IoMdArrowRoundUp',
  ArrowUp = 'IoMdArrowUp',

  At = 'IoMdAt',
  Attach = 'IoMdAttach',
  Backspace = 'IoMdBackspace',
  Barcode = 'IoMdBarcode',
  Baseball = 'IoMdBaseball',
  Basket = 'IoMdBasket',
  Basketball = 'IoMdBasketball',
  BatteryDead = 'IoMdBatteryDead',
  BatteryFull = 'IoMdBatteryFull',
  BatteryCharging = 'IoMdBatteryCharging',
  Beaker = 'IoMdBeaker',
  Bed = 'IoMdBed',
  Beer = 'IoMdBeer',
  Bicycle = 'IoMdBicycle',
  Bluetooth = 'IoMdBluetooth',
  Boat = 'IoMdBoat',
  Body = 'IoMdBody',
  Bonfire = 'IoMdBonfire',
  Book = 'IoMdBook',
  Bookmark = 'IoMdBookmark',
  Bookmarks = 'IoMdBookmarks',
  Bowtie = 'IoMdBowtie',
  Briefcase = 'IoMdBriefcase',
  Browsers = 'IoMdBrowsers',
  Brush = 'IoMdBrush',
  Bug = 'IoMdBug',
  Build = 'IoMdBuild',
  Bulb = 'IoMdBulb',
  Bus = 'IoMdBus',
  Business = 'IoMdBusiness',
  Cafe = 'IoMdCafe',
  Calculator = 'IoMdCalculator',
  Calendar = 'IoMdCalendar',
  Call = 'IoMdCall',
  Camera = 'IoMdCamera',
  Car = 'IoMdCar',
  Card = 'IoMdCard',
  Cart = 'IoMdCart',
  Cash = 'IoMdCash',
  Cellular = 'IoMdCellular',
  Clipboard = 'IoMdClipboard',
  Clock = 'IoMdClock',
  Close = 'IoMdClose',
  CloseCircle = 'IoMdCloseCircle',
  CloseCircleOutline = 'IoMdCloseCircleOutline',
  Cloud = 'IoMdCloud',
  CloudCircle = 'IoMdCloudCircle',
  CloudDone = 'IoMdCloudDone',
  CloudDownload = 'IoMdCloudDownload',
  CloudOutline = 'IoMdCloudOutline',
  CloudUpload = 'IoMdCloudUpload',
  Cloudy = 'IoMdCloudy',
  CloudyNight = 'IoMdCloudyNight',
  Code = 'IoMdCode',
  CodeDownload = 'IoMdCodeDownload',
  CodeWorking = 'IoMdCodeWorking',
  Cog = 'IoMdSettings',
  ColorFill = 'IoMdColorFill',
  ColorFilter = 'IoMdColorFilter',
  ColorPalette = 'IoMdColorPalette',
  ColorWand = 'IoMdColorWand',
  Compass = 'IoMdCompass',
  Construct = 'IoMdConstruct',
  Contact = 'IoMdContact',
  Contacts = 'IoMdContacts',
  Contract = 'IoMdContract',
  Contrast = 'IoMdContrast',
  Copy = 'IoMdCopy',
  Create = 'IoMdCreate',
  Crop = 'IoMdCrop',
  Cube = 'IoMdCube',
  Cut = 'IoMdCut',
  Desktop = 'IoMdDesktop',
  Disc = 'IoMdDisc',
  Document = 'IoMdDocument',
  DoneAll = 'IoMdDoneAll',
  Download = 'IoMdDownload',
  Easel = 'IoMdEasel',

  // wie deine Vorlage: Edit = Create
  Edit = 'IoMdCreate',

  Egg = 'IoMdEgg',
  Exit = 'IoMdExit',
  Expand = 'IoMdExpand',
  Eye = 'IoMdEye',
  EyeOff = 'IoMdEyeOff',
  Fastforward = 'IoMdFastforward',
  Female = 'IoMdFemale',
  Filing = 'IoMdFiling',
  Film = 'IoMdFilm',
  FingerPrint = 'IoMdFingerPrint',
  Fitness = 'IoMdFitness',
  Flag = 'IoMdFlag',
  Flame = 'IoMdFlame',
  Flash = 'IoMdFlash',
  Flashlight = 'IoMdFlashlight',
  FlashOff = 'IoMdFlashOff',
  Flask = 'IoMdFlask',
  Flower = 'IoMdFlower',
  Folder = 'IoMdFolder',
  FolderOpen = 'IoMdFolderOpen',
  Football = 'IoMdFootball',
  Funnel = 'IoMdFunnel',
  Gift = 'IoMdGift',

  GitBranch = 'IoMdGitBranch',
  GitCommit = 'IoMdGitCommit',
  GitCompare = 'IoMdGitCompare',
  GitMerge = 'IoMdGitMerge',
  GitNetwork = 'IoMdGitNetwork',
  GitPullRequest = 'IoMdGitPullRequest',

  Glasses = 'IoMdGlasses',
  Globe = 'IoMdGlobe',
  Grid = 'IoMdGrid',
  Hammer = 'IoMdHammer',
  Hand = 'IoMdHand',
  Happy = 'IoMdHappy',
  Headset = 'IoMdHeadset',
  Heart = 'IoMdHeart',
  HeartDislike = 'IoMdHeartDislike',
  HeartEmpty = 'IoMdHeartEmpty',
  HeartHalf = 'IoMdHeartHalf',
  Help = 'IoMdHelp',
  HelpBuoy = 'IoMdHelpBuoy',
  HelpCircle = 'IoMdHelpCircle',
  HelpCircleOutline = 'IoMdHelpCircleOutline',
  Home = 'IoMdHome',
  Hourglass = 'IoMdHourglass',

  Chatboxes = 'IoMdChatboxes',
  Chatbubbles = 'IoMdChatbubbles',
  Checkbox = 'IoMdCheckbox',
  CheckboxOutline = 'IoMdCheckboxOutline',
  Checkmark = 'IoMdCheckmark',
  CheckmarkCircle = 'IoMdCheckmarkCircle',
  CheckmarkCircleOutline = 'IoMdCheckmarkCircleOutline',

  IceCream = 'IoMdIceCream',
  Image = 'IoMdImage',
  Images = 'IoMdImages',
  Infinite = 'IoMdInfinite',
  Information = 'IoMdInformation',
  InformationCircle = 'IoMdInformationCircle',
  InformationCircleOutline = 'IoMdInformationCircleOutline',
  Jet = 'IoMdJet',
  Journal = 'IoMdJournal',
  Key = 'IoMdKey',
  Keypad = 'IoMdKeypad',
  Laptop = 'IoMdLaptop',
  Leaf = 'IoMdLeaf',
  Link = 'IoMdLink',
  List = 'IoMdList',
  ListBox = 'IoMdListBox',
  Locate = 'IoMdLocate',
  Locked = 'IoMdLock',
  LogIn = 'IoMdLogIn',
  LogOut = 'IoMdLogOut',
  Magnet = 'IoMdMagnet',
  Mail = 'IoMdMail',
  MailOpen = 'IoMdMailOpen',
  MailUnread = 'IoMdMailUnread',
  Male = 'IoMdMale',
  Man = 'IoMdMan',
  Map = 'IoMdMap',
  Medal = 'IoMdMedal',
  Medical = 'IoMdMedical',
  Medkit = 'IoMdMedkit',
  Megaphone = 'IoMdMegaphone',
  Menu = 'IoMdMenu',
  Mic = 'IoMdMic',
  MicOff = 'IoMdMicOff',
  Microphone = 'IoMdMicrophone',
  Moon = 'IoMdMoon',
  More = 'IoMdMore',
  Move = 'IoMdMove',
  MusicalNote = 'IoMdMusicalNote',
  MusicalNotes = 'IoMdMusicalNotes',
  Navigate = 'IoMdNavigate',
  Notifications = 'IoMdNotifications',
  NotificationsOff = 'IoMdNotificationsOff',
  NotificationsOutline = 'IoMdNotificationsOutline',
  Nuclear = 'IoMdNuclear',
  Nutrition = 'IoMdNutrition',
  Open = 'IoMdOpen',
  Options = 'IoMdOptions',
  Outlet = 'IoMdOutlet',
  Paper = 'IoMdPaper',
  PaperPlane = 'IoMdPaperPlane',
  PartlySunny = 'IoMdPartlySunny',
  Pause = 'IoMdPause',
  Paw = 'IoMdPaw',
  People = 'IoMdPeople',
  Person = 'IoMdPerson',
  PersonAdd = 'IoMdPersonAdd',
  PhoneLandscape = 'IoMdPhoneLandscape',
  PhonePortrait = 'IoMdPhonePortrait',
  Photos = 'IoMdPhotos',
  Pie = 'IoMdPie',
  Pin = 'IoMdPin',
  Pint = 'IoMdPint',
  Pizza = 'IoMdPizza',
  Planet = 'IoMdPlanet',
  Play = 'IoMdPlay',
  PlayCircle = 'IoMdPlayCircle',
  Podium = 'IoMdPodium',
  Power = 'IoMdPower',
  Pricetag = 'IoMdPricetag',
  Pricetags = 'IoMdPricetags',
  Print = 'IoMdPrint',
  Pulse = 'IoMdPulse',
  QrScanner = 'IoMdQrScanner',
  Quote = 'IoMdQuote',
  Radio = 'IoMdRadio',
  RadioButtonOff = 'IoMdRadioButtonOff',
  RadioButtonOn = 'IoMdRadioButtonOn',
  Rainy = 'IoMdRainy',
  Recording = 'IoMdRecording',
  Redo = 'IoMdRedo',
  Refresh = 'IoMdRefresh',
  RefreshCircle = 'IoMdRefreshCircle',
  Remove = 'IoMdRemove',
  RemoveCircle = 'IoMdRemoveCircle',
  RemoveCircleOutline = 'IoMdRemoveCircleOutline',
  Reorder = 'IoMdReorder',
  Repeat = 'IoMdRepeat',
  Resize = 'IoMdResize',
  Restaurant = 'IoMdRestaurant',
  ReturnLeft = 'IoMdReturnLeft',
  ReturnRight = 'IoMdReturnRight',
  ReverseCamera = 'IoMdReverseCamera',
  Rewind = 'IoMdRewind',
  Ribbon = 'IoMdRibbon',
  Rocket = 'IoMdRocket',
  Rose = 'IoMdRose',
  Sad = 'IoMdSad',
  Save = 'IoMdSave',
  Search = 'IoMdSearch',
  Send = 'IoMdSend',
  Settings = 'IoMdSettings',
  Share = 'IoMdShare',
  ShareAlt = 'IoMdShareAlt',
  Shirt = 'IoMdShirt',
  Shuffle = 'IoMdShuffle',
  School = 'IoMdSchool',
  SkipBackward = 'IoMdSkipBackward',
  SkipForward = 'IoMdSkipForward',
  Snow = 'IoMdSnow',
  Speedometer = 'IoMdSpeedometer',
  Square = 'IoMdSquare',
  SquareOutline = 'IoMdSquareOutline',
  Star = 'IoMdStar',
  StarHalf = 'IoMdStarHalf',
  StarOutline = 'IoMdStarOutline',
  Stats = 'IoMdStats',
  Stopwatch = 'IoMdStopwatch',
  Subway = 'IoMdSubway',
  Sunny = 'IoMdSunny',
  Swap = 'IoMdSwap',
  Switch = 'IoMdSwitch',
  Sync = 'IoMdSync',
  TabletLandscape = 'IoMdTabletLandscape',
  TabletPortrait = 'IoMdTabletPortrait',
  Tennisball = 'IoMdTennisball',
  Text = 'IoMdText',
  Thermometer = 'IoMdThermometer',
  ThumbsDown = 'IoMdThumbsDown',
  ThumbsUp = 'IoMdThumbsUp',
  Thunderstorm = 'IoMdThunderstorm',
  Time = 'IoMdTime',
  Timer = 'IoMdTimer',
  Today = 'IoMdToday',
  Train = 'IoMdTrain',
  Transgender = 'IoMdTransgender',
  Trash = 'IoMdTrash',
  TrendingDown = 'IoMdTrendingDown',
  TrendingUp = 'IoMdTrendingUp',
  Trophy = 'IoMdTrophy',
  Tv = 'IoMdTv',
  Umbrella = 'IoMdUmbrella',
  Undo = 'IoMdUndo',
  Unlocked = 'IoMdUnlock',
  Videocam = 'IoMdVideocam',
  VolumeHigh = 'IoMdVolumeHigh',
  VolumeLow = 'IoMdVolumeLow',
  VolumeMute = 'IoMdVolumeMute',
  VolumeOff = 'IoMdVolumeOff',
  Walk = 'IoMdWalk',
  Wallet = 'IoMdWallet',
  Warning = 'IoMdWarning',
  Water = 'IoMdWater',
  Watch = 'IoMdWatch',
  Wifi = 'IoMdWifi',
  Wine = 'IoMdWine',
  Woman = 'IoMdWoman',
}